sed -i -e 's/PIECEPOINTS/A1/g' pygone-mini.py
sed -i -e 's/ATTACKPOINTS/A2/g' pygone-mini.py
sed -i -e 's/PPSQT/A3/g' pygone-mini.py
sed -i -e 's/NPSQT/A4/g' pygone-mini.py
sed -i -e 's/BPSQT/A5/g' pygone-mini.py
sed -i -e 's/RPSQT/A6/g' pygone-mini.py
sed -i -e 's/QPSQT/A7/g' pygone-mini.py
sed -i -e 's/KPSQT/A8/g' pygone-mini.py
sed -i -e 's/ALLPSQT/A9/g' pygone-mini.py
sed -i -e 's/MATESCORE/A0/g' pygone-mini.py
sed -i -e 's/letter_to_number/B1/g' pygone-mini.py
sed -i -e 's/number_to_letter/B2/g' pygone-mini.py
sed -i -e 's/set_default_board_state/B31/g' pygone-mini.py
sed -i -e 's/set_board_state/B32/g' pygone-mini.py
sed -i -e 's/board_state/B3/g' pygone-mini.py
sed -i -e 's/played_move_count/B4/g' pygone-mini.py
sed -i -e 's/white_valid_moves/B5/g' pygone-mini.py
sed -i -e 's/black_valid_moves/B6/g' pygone-mini.py
sed -i -e 's/white_attack_locations/B7/g' pygone-mini.py
sed -i -e 's/black_attack_locations/B8/g' pygone-mini.py
sed -i -e 's/white_king_location/B9/g' pygone-mini.py
sed -i -e 's/black_king_location/B0/g' pygone-mini.py
sed -i -e 's/move_list_pieces/C11/g' pygone-mini.py
sed -i -e 's/move_list/C1/g' pygone-mini.py
sed -i -e 's/uci_coordinate/C2/g' pygone-mini.py
sed -i -e 's/reverse_promotion/C3/g' pygone-mini.py
sed -i -e 's/reverse_castle/C4/g' pygone-mini.py
sed -i -e 's/from_letter_number/C5/g' pygone-mini.py
sed -i -e 's/from_number/C6/g' pygone-mini.py
sed -i -e 's/to_letter_number/C7/g' pygone-mini.py
sed -i -e 's/to_number/C8/g' pygone-mini.py
sed -i -e 's/override_from_piece/C91/g' pygone-mini.py
sed -i -e 's/from_piece/C9/g' pygone-mini.py
sed -i -e 's/override_to_piece/C01/g' pygone-mini.py
sed -i -e 's/to_piece/C0/g' pygone-mini.py
sed -i -e 's/apply_move/D1/g' pygone-mini.py
sed -i -e 's/rook_offset/D2/g' pygone-mini.py
sed -i -e 's/promote/D3/g' pygone-mini.py
sed -i -e 's/make_move/D4/g' pygone-mini.py
sed -i -e 's/apply_move/D5/g' pygone-mini.py
sed -i -e 's/undo_move/D6/g' pygone-mini.py
sed -i -e 's/show_board/D7/g' pygone-mini.py
sed -i -e 's/get_valid_moves/D8/g' pygone-mini.py
sed -i -e 's/white_attack_pieces/D9/g' pygone-mini.py
sed -i -e 's/black_attack_pieces/D0/g' pygone-mini.py
sed -i -e 's/eval_state/E1/g' pygone-mini.py
sed -i -e 's/temp_row/E21/g' pygone-mini.py
sed -i -e 's/temp_col/E22/g' pygone-mini.py
sed -i -e 's/rowIncrement/E23/g' pygone-mini.py
sed -i -e 's/colIncrement/E24/g' pygone-mini.py
sed -i -e 's/row/E2/g' pygone-mini.py
sed -i -e 's/column/E3/g' pygone-mini.py
sed -i -e 's/eval_state/E4/g' pygone-mini.py
sed -i -e 's/white_start_coordinate/E5/g' pygone-mini.py
sed -i -e 's/black_start_coordinate/E6/g' pygone-mini.py
sed -i -e 's/is_white/E7/g' pygone-mini.py
sed -i -e 's/k_move/E81/g' pygone-mini.py
sed -i -e 's/king_moves/E8/g' pygone-mini.py
sed -i -e 's/eval_piece/E9/g' pygone-mini.py
sed -i -e 's/can_capture/E0/g' pygone-mini.py
sed -i -e 's/dest/F1/g' pygone-mini.py
sed -i -e 's/night_moves/F3/g' pygone-mini.py
sed -i -e 's/chosen_move/F41/g' pygone-mini.py
sed -i -e 's/position_move/F42/g' pygone-mini.py
sed -i -e 's/n_move/F4/g' pygone-mini.py
sed -i -e 's/horizontal_moves/F5/g' pygone-mini.py
sed -i -e 's/h_move/F6/g' pygone-mini.py
sed -i -e 's/all_moves/F7/g' pygone-mini.py
sed -i -e 's/old_move/F81/g' pygone-mini.py
sed -i -e 's/a_move/F8/g' pygone-mini.py
sed -i -e 's/move_copy/F9/g' pygone-mini.py
sed -i -e 's/move_string/F0/g' pygone-mini.py
sed -i -e 's/override_remove/G1/g' pygone-mini.py
sed -i -e 's/get_side_moves/G2/g' pygone-mini.py
sed -i -e 's/board_evaluation/G3/g' pygone-mini.py
sed -i -e 's/Search/G4/g' pygone-mini.py
sed -i -e 's/last_move/G5/g' pygone-mini.py
sed -i -e 's/end_time/G6/g' pygone-mini.py
sed -i -e 's/iterative_search/G71/g' pygone-mini.py
sed -i -e 's/b_search_pv/G72/g' pygone-mini.py
sed -i -e 's/search/G7/g' pygone-mini.py
sed -i -e 's/max_time/G8/g' pygone-mini.py
sed -i -e 's/local_board/G9/g' pygone-mini.py
sed -i -e 's/global_score/G0/g' pygone-mini.py
sed -i -e 's/poss_mvs/H1/g' pygone-mini.py
sed -i -e 's/local_score/H2/g' pygone-mini.py
sed -i -e 's/original_alpha/H31/g' pygone-mini.py
sed -i -e 's/alpha/H3/g' pygone-mini.py
sed -i -e 's/beta/H4/g' pygone-mini.py
sed -i -e 's/min_value/H5/g' pygone-mini.py
sed -i -e 's/max_value/H6/g' pygone-mini.py
sed -i -e 's/check_terminal/H7/g' pygone-mini.py
sed -i -e 's/game_board/H8/g' pygone-mini.py
sed -i -e 's/Board/H9/g' pygone-mini.py
sed -i -e 's/offset_moves/H0/g' pygone-mini.py
sed -i -e 's/go_board/I1/g' pygone-mini.py
sed -i -e 's/white_time/I2/g' pygone-mini.py
sed -i -e 's/black_time/I3/g' pygone-mini.py
sed -i -e 's/go_depth/I4/g' pygone-mini.py
sed -i -e 's/args/I5/g' pygone-mini.py
sed -i -e 's/elapsed_time/I6/g' pygone-mini.py
sed -i -e 's/move_time/I7/g' pygone-mini.py
sed -i -e 's/start_time/I8/g' pygone-mini.py
sed -i -e 's/in_check/I9/g' pygone-mini.py
sed -i -e 's/TTEXACT/I0/g' pygone-mini.py
sed -i -e 's/TTLOWER/J1/g' pygone-mini.py
sed -i -e 's/TTUPPER/J2/g' pygone-mini.py
sed -i -e 's/iterative_score/J3/g' pygone-mini.py
sed -i -e 's/iterative_move/J4/g' pygone-mini.py
sed -i -e 's/negamax/J5/g' pygone-mini.py
sed -i -e 's/transposition_table_lookup/J6/g' pygone-mini.py
sed -i -e 's/tt_entry/J7/g' pygone-mini.py
sed -i -e 's/update_transposition_table_entry/J8/g' pygone-mini.py
sed -i -e 's/board_to_hash/J9/g' pygone-mini.py
sed -i -e 's/board_hash/J0/g' pygone-mini.py
sed -i -e 's/TranspositionTableEntry/K1/g' pygone-mini.py
sed -i -e 's/tt_set/K2/g' pygone-mini.py
sed -i -e 's/reset/K3/g' pygone-mini.py
sed -i -e 's/time_move_calc/K4/g' pygone-mini.py
sed -i -e 's/WHITE_PIECES/K5/g' pygone-mini.py
sed -i -e 's/BLACK_PIECES/K6/g' pygone-mini.py
sed -i -e 's/start_coordinate/K7/g' pygone-mini.py
sed -i -e 's/s_move/K7/g' pygone-mini.py
sed -i -e 's/attacked/K8/g' pygone-mini.py
sed -i -e 's/attacker/K9/g' pygone-mini.py
sed -i -e 's/b_eval/K0/g' pygone-mini.py
sed -i -e 's/ping_time/L1/g' pygone-mini.py
sed -i -e 's/quiesce/L2/g' pygone-mini.py
sed -i -e 's/multiplier/L3/g' pygone-mini.py
sed -i -e 's/poss_caps/L4/g' pygone-mini.py
sed -i -e 's/v_nodes/L5/g' pygone-mini.py
sed -i -e 's/v_depth/L6/g' pygone-mini.py
sed -i -e 's/s_depth/L7/g' pygone-mini.py
sed -i -e 's/v_score/L8/g' pygone-mini.py
sed -i -e 's/delta/L9/g' pygone-mini.py
sed -i -e 's/score_white/L0/g' pygone-mini.py
sed -i -e 's/check_string/M1/g' pygone-mini.py

sed -i -e 's/piece/Z1/g' pygone-mini.py


sed -i -e 's/# Created by pyminifier (https:\/\/github.com\/liftoff\/pyminifier)//g' pygone-mini.py