#!/usr/bin/env pypy3
from pathlib import Path

file = Path("pygone-mini.py")
code = file.read_text()

# Define all replacements here
replacements = {
    # Constants / dictionaries
    "NUMERICAL_PIECEPOINTS": "A8",
    "PIECEPOINTS": "A9",
    "NUMERICAL_ALLPSQT": "B8",
    "ALLPSQT": "B9",
    "set_piece_num": "C8",
    "set_piece": "C9",
    "set_row": "D9",
    "set_column": "E9",
    "WHITE_PIECES": "F9",
    "BLACK_PIECES": "G9",

    # Search class attributes
    "v_nodes": "H9",
    "v_depth": "I9",
    "end_time": "J9",
    "critical_time": "K9",
    "tt_bucket": "L9",
    "eval_exact": "M9",
    "eval_upper": "N9",
    "eval_lower": "O9",
    "eval_mate_upper": "P9",

    # Board class attributes
    "board_string": "Q9",
    "hash": "R9",
    "ZOBRIST": "S9",
    "ZOBRIST_CASTLE": "T9",
    "ZOBRIST_EP": "U9",
    "ZOBRIST_SIDE": "V9",
    "played_move_count": "W9",
    "white_castling": "X9",
    "black_castling": "Y9",
    "self": "Z9",
    "white_king_position": "Z1",
    "black_king_position": "aa",
    "rolling_score": "ab",
    "piece_count": "ac",
    "en_passant_file_index": "ae",
    "move_counter": "af",

    # Board class methods
    "init_zobrist": "ah",
    "unpack_coordinate": "ai",
    "position_to_coordinate": "aj",
    "coordinate_to_position": "ak",
    "mutate_board": "al",
    "get_moves": "am",
    "number_to_letter": "an",
    "apply_move": "ao",
    "make_move": "ap",
    "nullmove": "aq",
    "board_copy": "ar",
    "get_piece_count": "as1",
    "is_endgame": "at",
    "move_sort": "au",
    "print_board": "av",
    "calculate_score": "aw",
    "passer_pawn": "ax",
    "stacked_pawn": "ay",
    "str_board": "az",
    "generate_valid_captures": "ba",
    "generate_valid_moves": "bb",
    "is_in_check": "bc9",
    "in_check": "bc",
    "attack_position": "bd",
    
    "v_score": "be",
    "v_time": "bf",
    "v_nps": "bg",
    "v_pv": "bh",
    "local_board": "bi",
    "local_score": "bj",
    "best_move": "bk",
    "is_pv_node": "bl",
    "reset": "bm",
    "elapsed_time": "bn",
    "counter": "bo",
    "pv_entry": "bp",
    "pv_board": "bq",
    "repetitions": "br",
    "valid_pieces": "bs",
    "cut_boundary": "bt",
    "best_score": "bu",
    "is_white_king_side": "bv2",
    "is_white_to_move": "bv1",
    "is_white": "bv",
    "pieces": "bw",
    "played_moves": "by",
    "s_move": "bz",
    "moved_board": "ca",
    "is_quiet": "cb",
    "r_depth": "cc",
    "set_board": "cd",
    "prow": "ce",
    "old_piece_num": "cf1",
    "old_piece": "cf",
    "column": "cg",
    "Board": "ch",
    "board_position": "ci",
    "zobrist": "cj",
    "uci_coordinate": "ck",
    "start_coordinate": "cl",
    "new_piece_num": "cm1",
    "new_piece": "cm",
    "to_number": "cn",
    "from_number": "co",
    "from_piece_base_num": "cp2",
    "from_piece_num": "cp1",
    "from_piece": "cp",
    "to_piece_base_num": "cq1",
    "to_piece": "cq",
    "to_offset": "cr",
    "from_offset": "cs",
    "promote_char": "ct1",
    "promote_base_num": "ct2",
    "promote": "ct",
    "p_offset": "cu",
    "start_positions": "cv",
    "captures_only": "cw",
    "max_row": "cx",
    "min_row": "cy",
    "valid_bw": "cz",
    "piece_lower": "da",
    "piece_move": "db",
    "to_position": "dc",
    "eval_piece_num": "dd1",
    "eval_piece": "dd",
    "dest": "de",
    "king_position": "df",
    "is_promotion_rank": "dg1",
    "prom": "dg",
    "print_string": "dh",
    "print_to_terminal": "di",
    "game_board": "dj",
    "searcher": "dk",
    "Search": "dl",
    "main": "dm",
    "line": "dn",
    "position_move": "do",
    "moves": "dp",
    "move_time": "dq",
    "p_piece": "dr",
    
    "EMPTY": "ds",
    "OFF_BOARD": "dt",
    "CHAR_TO_NUM": "du",
    "NUM_TO_CHAR": "dx",
    "psqt_values": "dy",
    "char_piece": "dz",
    "num_piece": "ea",
    "value": "eb",
    "board_str": "eb",
    "piece_num": "ec",
    "count": "ed",
    "has_queen": "ee",
    "opponent_min": "ef",
    "opponent_max": "eg",
    "char_list": "eh",
    
    "player_piece_min": "ei",
    "player_piece_max": "ej",
    "opponent_piece_min": "ek",
    "opponent_piece_max": "el",
    "pawn_offset_multiplier": "em",
    "pawn_start_row_min": "en",
    "pawn_start_row_max": "eo",
    "piece_base_num": "ep",
    "one_step": "eq",
    "two_step": "er",
    "dd_num": "es",    
    "file_offset": "et",
    "rank_offset": "eu",
    "piece_char": "ev",
    "is_opponent_piece": "ew",
    "is_empty_square": "ex",
    "attacker_min": "ey",
    "attacker_max": "ez",
    "attack_offsets": "fa",
    
    "tt_entry": "ta",
    "tt_value": "tb",
    "tt_flag": "tc",
    "tt_depth": "td",
    "tt_move": "te",
    
    "print_stats": "ps",
    "start_time": "st",
    
    "original_alpha": "yc",
    "alpha": "ya",
    "beta": "yb",
    
    "pos": "za",
    "piece": "zb",
    "square": "zc",
    "en_passant_offset": "zd",
    "en_passant": "ze",
    "offset": "zf",
    "coordinate": "zg",
    
    "iterative_search": "zi",
    "q_search": "zq",
    "l_board_state": "zs",
    "board_state": "zt",
    "board": "zu",
    "search": "zz",

    # Built-ins / keywords
    "True": "1",
    "False": "0",
}

# Apply replacements (longest first to prevent partial overlaps)
for old, new in sorted(replacements.items(), key=lambda kv: -len(kv[0])):
    code = code.replace(old, new)

# Write back
file.write_text(code)

replacements = {
    "KeyzuInterrupt": "KeyboardInterrupt",
    "zaition": "position",
}

# Apply replacements (longest first to prevent partial overlaps)
for old, new in sorted(replacements.items(), key=lambda kv: -len(kv[0])):
    code = code.replace(old, new)

# Write back
file.write_text(code)