sed -i -e 's/openingBook/A/g' pygone-mini.py
sed -i -e 's/piecePoints/B/g' pygone-mini.py
sed -i -e 's/attackPoints/C/g' pygone-mini.py
sed -i -e 's/pPSQT/D/g' pygone-mini.py
sed -i -e 's/nPSQT/E/g' pygone-mini.py
sed -i -e 's/bPSQT/F/g' pygone-mini.py
sed -i -e 's/rPSQT/G/g' pygone-mini.py
sed -i -e 's/qPSQT/H/g' pygone-mini.py
sed -i -e 's/kPSQT/I/g' pygone-mini.py
sed -i -e 's/allPSGT/J/g' pygone-mini.py
sed -i -e 's/boardState/K/g' pygone-mini.py
sed -i -e 's/playedMoveCount/L/g' pygone-mini.py
sed -i -e 's/whiteValidMoves/M/g' pygone-mini.py
sed -i -e 's/blackValidMoves/N/g' pygone-mini.py
sed -i -e 's/whiteAttackLocations/O/g' pygone-mini.py
sed -i -e 's/blackAttackLocations/P/g' pygone-mini.py
sed -i -e 's/whiteKingLocation/Q/g' pygone-mini.py
sed -i -e 's/blackKingLocation/R/g' pygone-mini.py
sed -i -e 's/moveList/S/g' pygone-mini.py
sed -i -e 's/lastMove/T/g' pygone-mini.py
# sed -i -e 's/nodes/U/g' pygone-mini.py
sed -i -e 's/setDefaultBoardState/V/g' pygone-mini.py
sed -i -e 's/setBoardState/W/g' pygone-mini.py
sed -i -e 's/makeMove/X/g' pygone-mini.py
sed -i -e 's/uciCoordinate/Y/g' pygone-mini.py
sed -i -e 's/fromCoordinate/D1/g' pygone-mini.py
sed -i -e 's/toCoordinate/D2/g' pygone-mini.py
sed -i -e 's/fromLetterNumber/D3/g' pygone-mini.py
sed -i -e 's/toLetterNumber/D4/g' pygone-mini.py
sed -i -e 's/fromLetter/D5/g' pygone-mini.py
sed -i -e 's/fromNumber/D6/g' pygone-mini.py
sed -i -e 's/toLetter/D7/g' pygone-mini.py
sed -i -e 's/toNumber/D8/g' pygone-mini.py
sed -i -e 's/fromPiece/D9/g' pygone-mini.py
sed -i -e 's/toPiece/D0/g' pygone-mini.py
sed -i -e 's/promote/a/g' pygone-mini.py
sed -i -e 's/letterToNumber/b/g' pygone-mini.py
sed -i -e 's/numberToLetter/c/g' pygone-mini.py
sed -i -e 's/showBoard/d/g' pygone-mini.py
sed -i -e 's/getValidMoves/e/g' pygone-mini.py
sed -i -e 's/whiteAttackPieces/f/g' pygone-mini.py
sed -i -e 's/blackAttackPieces/g/g' pygone-mini.py
sed -i -e 's/evalState/h/g' pygone-mini.py
sed -i -e 's/whiteStartCoordinate/i/g' pygone-mini.py
sed -i -e 's/blackStartCoordinate/j/g' pygone-mini.py
sed -i -e 's/isWhite/k/g' pygone-mini.py
sed -i -e 's/kMoves/l/g' pygone-mini.py
sed -i -e 's/bestMoveFinal/m/g' pygone-mini.py
sed -i -e 's/bestMove/n/g' pygone-mini.py
sed -i -e 's/canCapture/o/g' pygone-mini.py
sed -i -e 's/tempRow/p/g' pygone-mini.py
sed -i -e 's/tempCol/q/g' pygone-mini.py
sed -i -e 's/rowIncrement/r/g' pygone-mini.py
sed -i -e 's/colIncrement/s/g' pygone-mini.py
sed -i -e 's/row/t/g' pygone-mini.py
sed -i -e 's/column/u/g' pygone-mini.py
sed -i -e 's/evalPiece/v/g' pygone-mini.py
sed -i -e 's/removeIllegalMoves/w/g' pygone-mini.py
sed -i -e 's/masterMoves/A0/g' pygone-mini.py
sed -i -e 's/legalMovesBoard/A1/g' pygone-mini.py
sed -i -e 's/kLoc/A2/g' pygone-mini.py
sed -i -e 's/availMvs/A3/g' pygone-mini.py
sed -i -e 's/boardEvaluation/A4/g' pygone-mini.py
sed -i -e 's/bEval/A5/g' pygone-mini.py
sed -i -e 's/minimaxRoot/A6/g' pygone-mini.py
sed -i -e 's/minimax/A7/g' pygone-mini.py
sed -i -e 's/lglMvs/A8/g' pygone-mini.py
sed -i -e 's/possMvs/A9/g' pygone-mini.py
sed -i -e 's/originalState/AA/g' pygone-mini.py
sed -i -e 's/startTime/AB/g' pygone-mini.py
sed -i -e 's/boardEvaluation/AC/g' pygone-mini.py
sed -i -e 's/startTime/AD/g' pygone-mini.py
sed -i -e 's/boardEvaluation/AE/g' pygone-mini.py
sed -i -e 's/originalState/AF/g' pygone-mini.py
sed -i -e 's/endTime/AG/g' pygone-mini.py
sed -i -e 's/state/AH/g' pygone-mini.py
sed -i -e 's/moves/AI/g' pygone-mini.py
sed -i -e 's/nMove/AJ/g' pygone-mini.py
sed -i -e 's/localBoard/AK/g' pygone-mini.py
# sed -i -e 's/depth/AL/g' pygone-mini.py
sed -i -e 's/alpha/AM/g' pygone-mini.py
sed -i -e 's/beta/AN/g' pygone-mini.py
sed -i -e 's/isMaximizing/AO/g' pygone-mini.py
sed -i -e 's/offset/AP/g' pygone-mini.py
sed -i -e 's/key/x/g' pygone-mini.py
sed -i -e 's/piece/z/g' pygone-mini.py
sed -i -e 's/Board/Z/g' pygone-mini.py
sed -i -e 's/horizontalMoves/B0/g' pygone-mini.py
sed -i -e 's/hMove/B1/g' pygone-mini.py
sed -i -e 's/diagMoves/B2/g' pygone-mini.py
sed -i -e 's/dMove/B3/g' pygone-mini.py
sed -i -e 's/pastMoves/B4/g' pygone-mini.py
sed -i -e 's/moveString/B5/g' pygone-mini.py
sed -i -e 's/overrideRemove/B6/g' pygone-mini.py
sed -i -e 's/attacked/B7/g' pygone-mini.py
sed -i -e 's/attacker/B8/g' pygone-mini.py
sed -i -e 's/# Created by pyminifier (https:\/\/github.com\/liftoff\/pyminifier)//g' pygone-mini.py