sed -i -e 's/PIECEPOINTS/A/g' pygone-mini.py
sed -i -e 's/ALLPSQT/B/g' pygone-mini.py
sed -i -e 's/set_piece/C/g' pygone-mini.py
sed -i -e 's/set_row/D/g' pygone-mini.py
sed -i -e 's/set_column/E/g' pygone-mini.py
sed -i -e 's/WHITE_PIECES/F/g' pygone-mini.py
sed -i -e 's/BLACK_PIECES/G/g' pygone-mini.py
sed -i -e 's/EXACT/H/g' pygone-mini.py
sed -i -e 's/MATE_LOWER/I/g' pygone-mini.py
sed -i -e 's/MATE_UPPER/J/g' pygone-mini.py
sed -i -e 's/UPPER/K/g' pygone-mini.py
sed -i -e 's/LOWER/L/g' pygone-mini.py
sed -i -e 's/TO_MOVES/M/g' pygone-mini.py
sed -i -e 's/number_to_letter/N/g' pygone-mini.py
sed -i -e 's/to_number/O/g' pygone-mini.py
sed -i -e 's/print_string/P/g' pygone-mini.py
sed -i -e 's/print_to_terminal/Q/g' pygone-mini.py
sed -i -e 's/print_stats/R/g' pygone-mini.py
sed -i -e 's/v_depth/S/g' pygone-mini.py
sed -i -e 's/best_score/T/g' pygone-mini.py
sed -i -e 's/div_time/UU/g' pygone-mini.py
sed -i -e 's/v_time/U/g' pygone-mini.py
sed -i -e 's/v_nodes/V/g' pygone-mini.py
sed -i -e 's/v_nps/W/g' pygone-mini.py
sed -i -e 's/v_pv/X/g' pygone-mini.py
sed -i -e 's/unpack_coordinate/Y/g' pygone-mini.py
sed -i -e 's/uci_coordinate/A1/g' pygone-mini.py
sed -i -e 's/is_dead/A2/g' pygone-mini.py
sed -i -e 's/calculate_score/A4/g' pygone-mini.py
sed -i -e 's/generate_valid_moves/A5/g' pygone-mini.py
sed -i -e 's/Board/A6/g' pygone-mini.py
sed -i -e 's/board_state/A7/g' pygone-mini.py
sed -i -e 's/played_move_count/A8/g' pygone-mini.py
sed -i -e 's/move_list/A9/g' pygone-mini.py
sed -i -e 's/repetitions/A0/g' pygone-mini.py
sed -i -e 's/valid_moves/B/g' pygone-mini.py
sed -i -e 's/attack_squares/B1/g' pygone-mini.py
sed -i -e 's/white_castling/B2/g' pygone-mini.py
sed -i -e 's/black_castling/B3/g' pygone-mini.py
sed -i -e 's/white_king_position/B4/g' pygone-mini.py
sed -i -e 's/black_king_position/B5/g' pygone-mini.py
sed -i -e 's/rolling_score/B6/g' pygone-mini.py
sed -i -e 's/set_en_passant/B71/g' pygone-mini.py
sed -i -e 's/en_passant_offset/B72/g' pygone-mini.py
sed -i -e 's/en_passant/B7/g' pygone-mini.py
sed -i -e 's/apply_move/B8/g' pygone-mini.py
sed -i -e 's/from_letter_number/B9/g' pygone-mini.py
sed -i -e 's/from_number/B0/g' pygone-mini.py
sed -i -e 's/to_letter_number/C1/g' pygone-mini.py
sed -i -e 's/from_piece/C2/g' pygone-mini.py
sed -i -e 's/make_move/C4/g' pygone-mini.py
sed -i -e 's/nullmove/C5/g' pygone-mini.py
sed -i -e 's/str_board/C6/g' pygone-mini.py
sed -i -e 's/get_piece_count/C7/g' pygone-mini.py
sed -i -e 's/is_endgame/C8/g' pygone-mini.py
sed -i -e 's/total_pieces/C9/g' pygone-mini.py
sed -i -e 's/total_pawns/C0/g' pygone-mini.py
sed -i -e 's/p_offset/D11/g' pygone-mini.py
sed -i -e 's/offset/D1/g' pygone-mini.py
sed -i -e 's/local_score/D2/g' pygone-mini.py
sed -i -e 's/from_score_piece/D3/g' pygone-mini.py
sed -i -e 's/to_piece/D4/g' pygone-mini.py
sed -i -e 's/p_piece/D5/g' pygone-mini.py
sed -i -e 's/protected_pawns/D6/g' pygone-mini.py
sed -i -e 's/promote/D7/g' pygone-mini.py
sed -i -e 's/enemy_king_position/D8/g' pygone-mini.py
sed -i -e 's/score_pieces/D9/g' pygone-mini.py
sed -i -e 's/pawn_piece/D0/g' pygone-mini.py
sed -i -e 's/score_pawns/E11/g' pygone-mini.py
sed -i -e 's/pawns/E1/g' pygone-mini.py
sed -i -e 's/pawn_columns/E2/g' pygone-mini.py
sed -i -e 's/has_pawn/E3/g' pygone-mini.py
sed -i -e 's/is_reverse/E4/g' pygone-mini.py
sed -i -e 's/valid_pieces/E5/g' pygone-mini.py
sed -i -e 's/min_row/E6/g' pygone-mini.py
sed -i -e 's/max_row/E7/g' pygone-mini.py
sed -i -e 's/eval_state/E8/g' pygone-mini.py
sed -i -e 's/start_coordinate/E9/g' pygone-mini.py
sed -i -e 's/is_in_check/E01/g' pygone-mini.py
sed -i -e 's/in_check/E0/g' pygone-mini.py
sed -i -e 's/is_legal/F1/g' pygone-mini.py
sed -i -e 's/s_move/F2/g' pygone-mini.py
sed -i -e 's/piece_move/F3/g' pygone-mini.py
sed -i -e 's/to_column/F4/g' pygone-mini.py
sed -i -e 's/to_row/F5/g' pygone-mini.py
sed -i -e 's/eval_piece/F6/g' pygone-mini.py
sed -i -e 's/dest/F7/g' pygone-mini.py
sed -i -e 's/TABLE_LIMIT/F8/g' pygone-mini.py
sed -i -e 's/CONTEMPT/F9/g' pygone-mini.py
sed -i -e 's/Search/F0/g' pygone-mini.py
sed -i -e 's/end_time/G1/g' pygone-mini.py
sed -i -e 's/critical_time/G2/g' pygone-mini.py
sed -i -e 's/tt_bucket/G3/g' pygone-mini.py
sed -i -e 's/tt_moves/G4/g' pygone-mini.py
sed -i -e 's/perft_captures/G5/g' pygone-mini.py
sed -i -e 's/perft_checks/G6/g' pygone-mini.py
sed -i -e 's/moved_board/G7/g' pygone-mini.py
sed -i -e 's/prom/G8/g' pygone-mini.py
sed -i -e 's/reset/G9/g' pygone-mini.py
sed -i -e 's/is_perft/G01/g' pygone-mini.py
sed -i -e 's/run_perft/G0/g' pygone-mini.py
sed -i -e 's/iterative_search/H1/g' pygone-mini.py
sed -i -e 's/start_time/H2/g' pygone-mini.py
sed -i -e 's/initial_move/H3/g' pygone-mini.py
sed -i -e 's/lower_bound/H4/g' pygone-mini.py
sed -i -e 's/upper_bound/H5/g' pygone-mini.py
sed -i -e 's/score_cutoff/H6/g' pygone-mini.py
sed -i -e 's/best_move/H7/g' pygone-mini.py
sed -i -e 's/elapsed_time/H8/g' pygone-mini.py
sed -i -e 's/searcher/H91/g' pygone-mini.py
sed -i -e 's/parent_search/H92/g' pygone-mini.py
sed -i -e 's/q_search/H93/g' pygone-mini.py
sed -i -e 's/first_search/H94/g' pygone-mini.py
sed -i -e 's/root_search/H95/g' pygone-mini.py
sed -i -e 's/search/H9/g' pygone-mini.py
sed -i -e 's/parent_search/H0/g' pygone-mini.py
sed -i -e 's/tt_entry/I1/g' pygone-mini.py
sed -i -e 's/current_piece_count/I2/g' pygone-mini.py
sed -i -e 's/killer_score/I3/g' pygone-mini.py
sed -i -e 's/killer_board/I4/g' pygone-mini.py
sed -i -e 's/killer/I5/g' pygone-mini.py
sed -i -e 's/current_move_score/I6/g' pygone-mini.py
sed -i -e 's/game_board/I7/g' pygone-mini.py
sed -i -e 's/searcher/I8/g' pygone-mini.py
sed -i -e 's/start_moves/I91/g' pygone-mini.py
sed -i -e 's/played_moves/I92/g' pygone-mini.py
sed -i -e 's/moves/I9/g' pygone-mini.py
sed -i -e 's/position_move/I0/g' pygone-mini.py
sed -i -e 's/white_time/J1/g' pygone-mini.py
sed -i -e 's/black_time/J2/g' pygone-mini.py
sed -i -e 's/args/J3/g' pygone-mini.py
sed -i -e 's/result_score/JJ3/g' pygone-mini.py
sed -i -e 's/moved_piece_count/J4/g' pygone-mini.py
sed -i -e 's/best_score/J5/g' pygone-mini.py
sed -i -e 's/move_time/J6/g' pygone-mini.py
sed -i -e 's/out_string/J8/g' pygone-mini.py
sed -i -e 's/in_list/J9/g' pygone-mini.py
sed -i -e 's/string_count/J0/g' pygone-mini.py
sed -i -e 's/haystack/K1/g' pygone-mini.py
sed -i -e 's/needle/K2/g' pygone-mini.py
sed -i -e 's/board_string/K3/g' pygone-mini.py
sed -i -e 's/piece_count/K4/g' pygone-mini.py
sed -i -e 's/force_move/K5/g' pygone-mini.py
sed -i -e 's/all_dead/K6/g' pygone-mini.py
sed -i -e 's/v_score/K7/g' pygone-mini.py
sed -i -e 's/s_count/K8/g' pygone-mini.py
sed -i -e 's/king_piece/K9/g' pygone-mini.py
sed -i -e 's/piece_lower/K0/g' pygone-mini.py
sed -i -e 's/pv_node/L1/g' pygone-mini.py
sed -i -e 's/original_alpha/L2/g' pygone-mini.py
sed -i -e 's/alpha/L3/g' pygone-mini.py
sed -i -e 's/beta/L4/g' pygone-mini.py
sed -i -e 's/current_eval/L5/g' pygone-mini.py
sed -i -e 's/f_margin/L6/g' pygone-mini.py
sed -i -e 's/current_eval/L7/g' pygone-mini.py
sed -i -e 's/pieces/L8/g' pygone-mini.py
sed -i -e 's/r_value/L9/g' pygone-mini.py
sed -i -e 's/stand_pat/L0/g' pygone-mini.py
sed -i -e 's/tt_value/M1/g' pygone-mini.py
sed -i -e 's/tt_flag/M2/g' pygone-mini.py
sed -i -e 's/move_sort/M3/g' pygone-mini.py
sed -i -e 's/sorting/M4/g' pygone-mini.py
sed -i -e 's/k_score/M5/g' pygone-mini.py
sed -i -e 's/moves/M6/g' pygone-mini.py
sed -i -e 's/is_noisy/M7/g' pygone-mini.py
sed -i -e 's/reduce_depth/M8/g' pygone-mini.py
sed -i -e 's/move_counter/M9/g' pygone-mini.py
sed -i -e 's/tt_depth/M0/g' pygone-mini.py
sed -i -e 's/tt_move/N1/g' pygone-mini.py
sed -i -e 's/aspiration_window/N2/g' pygone-mini.py
sed -i -e 's/delta/N3/g' pygone-mini.py
sed -i -e 's/original_depth/N4/g' pygone-mini.py
sed -i -e 's/PROTECTED_PAWN_VALUE/N5/g' pygone-mini.py
sed -i -e 's/protected_pawn/N6/g' pygone-mini.py
sed -i -e 's/generate_valid_captures/N7/g' pygone-mini.py
sed -i -e 's/captures_only/N8/g' pygone-mini.py
sed -i -e 's/pawn_count/N9/g' pygone-mini.py
sed -i -e 's/STACKED_PAWN_VALUE/N0/g' pygone-mini.py
sed -i -e 's/king_position/O1/g' pygone-mini.py
sed -i -e 's/attack_position/O2/g' pygone-mini.py

sed -i -e 's/self/Z/g' pygone-mini.py
sed -i -e 's/row/Z1/g' pygone-mini.py
sed -i -e 's/piece/Z2/g' pygone-mini.py
sed -i -e 's/line/Z3/g' pygone-mini.py
sed -i -e 's/column/Z4/g' pygone-mini.py
sed -i -e 's/letter/Z6/g' pygone-mini.py
sed -i -e 's/coordinate/Z7/g' pygone-mini.py
sed -i -e 's/Entry/Z8/g' pygone-mini.py

sed -i -e 's/is_white/i/g' pygone-mini.py
sed -i -e 's/local_board/l/g' pygone-mini.py
sed -i -e 's/board/u/g' pygone-mini.py
sed -i -e 's/string_join/v/g' pygone-mini.py

sed -i -e 's/KeyuInterrupt/KeyboardInterrupt/g' pygone-mini.py
sed -i -e 's/perf_T4/perf_counter/g' pygone-mini.py

sed -i -e 's/True/1/g' pygone-mini.py
sed -i -e 's/False/0/g' pygone-mini.py

sed -i -e 's/# Created by pyminifier (https:\/\/github.com\/liftoff\/pyminifier)//g' pygone-mini.py